/// <reference types="node" />
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
  Kv3Double,
  Kv3Flagged,
  encodeTextKv3,
  isTextKv3,
  parseBinaryKv3,
  parseKv3,
  parseTextKv3,
  type Kv3Value,
} from "./kv3";
import { injectBuildIntoCache, injectBuildsIntoCache } from "./heroBuildCache";
import { encodeHeroBuild } from "./heroBuildExport";

// A real (binary v5, LZ4) cache file, with reference outputs generated by the Python `keyvalues3`
// library the Pyodide-based reader used — the parse tree as JSON, and the text-KV3 result of the
// exact injection the shipped Python glue performed. Regenerate with scripts/gen-kv3-fixtures.py.
const FIXTURES = new URL("../test/fixtures/", import.meta.url);
const cacheBytes = new Uint8Array(
  readFileSync(new URL("cached_hero_builds.kv3", FIXTURES)),
);
const expectedTree = JSON.parse(
  readFileSync(new URL("kv3-tree.json", FIXTURES), "utf8"),
);
const expectedInjected = readFileSync(new URL("kv3-injected.kv3", FIXTURES));

// The same deterministic stand-in blob the fixture generator appended.
const testBlob = Uint8Array.from(
  { length: 64 },
  (_, i) => (i * 37 + 11) & 0xff,
);

/** The Python fixture's JSON encoding: Maps → objects, blobs → {$bytes: hex}, doubles unwrapped. */
function jsonable(v: Kv3Value): unknown {
  if (v instanceof Uint8Array)
    return {
      $bytes: [...v].map((b) => b.toString(16).padStart(2, "0")).join(""),
    };
  if (v instanceof Map)
    return Object.fromEntries([...v].map(([k, x]) => [k, jsonable(x)]));
  if (Array.isArray(v)) return v.map(jsonable);
  if (v instanceof Kv3Double) return v.value;
  return v;
}

describe("parseBinaryKv3", () => {
  it("parses a real cache file identically to Python keyvalues3", () => {
    expect(jsonable(parseBinaryKv3(cacheBytes))).toEqual(expectedTree);
  });

  it("rejects non-KV3 bytes with a useful message", () => {
    expect(() => parseBinaryKv3(new Uint8Array(64))).toThrow(
      /not a binary kv3/i,
    );
  });

  it("names older KV3 versions instead of failing cryptically", () => {
    const v4 = new Uint8Array(cacheBytes);
    v4[0] = 0x04;
    expect(() => parseBinaryKv3(v4)).toThrow(/version 4/);
  });
});

describe("injectBuildIntoCache", () => {
  it("matches the Python pipeline byte-for-byte", () => {
    const out = injectBuildIntoCache(cacheBytes, testBlob);
    expect(Buffer.from(out).equals(expectedInjected)).toBe(true);
  });

  it("rejects a KV3 file without a Favorites list", () => {
    // Text KV3 isn't binary KV3 — but any parseable file lacking Favorites hits the same guard.
    expect(() => injectBuildIntoCache(new Uint8Array(64), testBlob)).toThrow();
  });

  it("appends every build of a batch, in order, in one parse", () => {
    // The batch export writes a build per hero you queue with. It cannot be a loop over the single
    // injector — that reads BINARY kv3 and emits TEXT, so the second pass would fail on its own
    // output — which is exactly what this pins.
    const second = new Uint8Array(testBlob.map((b) => b ^ 0x5a));
    const before = blobsIn(injectBuildsIntoCache(cacheBytes, []).bytes);
    const r = injectBuildsIntoCache(cacheBytes, [testBlob, second]);
    const after = blobsIn(r.bytes);
    // Neither stand-in blob parses as one of our builds, so both are appended.
    expect(r).toMatchObject({ replaced: 0, added: 2 });
    // Both are present, adjacent, in the order given — and nothing the file already held has moved
    // or been lost. They land at the end of `Favorites`, which is NOT the end of the file: later
    // keys carry blobs of their own, so this can't just read the last two.
    const at = after.indexOf(hex(testBlob));
    expect(at).toBeGreaterThanOrEqual(0);
    expect(after[at + 1]).toBe(hex(second));
    expect(after.filter((_, i) => i !== at && i !== at + 1)).toEqual(before);
  });

  it("adds nothing for an empty batch", () => {
    const r = injectBuildsIntoCache(cacheBytes, []);
    expect(r).toMatchObject({ replaced: 0, added: 0 });
    expect(blobsIn(r.bytes)).toHaveLength(
      blobsIn(injectBuildIntoCache(cacheBytes, testBlob)).length - 1,
    );
  });

  // The reason replacement exists: without it, every re-export left another copy behind and the
  // in-game browser filled up with stale duplicates of one build.
  it("replaces our previous build for the same hero instead of duplicating it", () => {
    const v1 = ourBuild(HERO_A, "Vibelock — Hero A (Emissary+)");
    const v2 = ourBuild(HERO_A, "Vibelock — Hero A (Oracle+)");
    const once = injectBuildsIntoCache(cacheBytes, [v1]);
    expect(once).toMatchObject({ replaced: 0, added: 1 });

    const twice = injectBuildsIntoCache(once.bytes, [v2]);
    expect(twice).toMatchObject({ replaced: 1, added: 0 });
    const blobs = blobsIn(twice.bytes);
    expect(blobs).toContain(hex(v2));
    expect(blobs).not.toContain(hex(v1));
    // Same length as after the first write — the rank changed, the entry did not multiply.
    expect(blobs).toHaveLength(blobsIn(once.bytes).length);
  });

  it("keeps our builds for other heroes, and never touches the player's own", () => {
    const mineA = ourBuild(HERO_A, "Vibelock — Hero A (Oracle+)");
    const mineB = ourBuild(HERO_B, "Vibelock — Hero B (Oracle+)");
    // Same hero as one of ours, but not our build — a build the player made themselves.
    const theirs = ourBuild(HERO_A, "my own Hero A build");
    const seeded = injectBuildsIntoCache(cacheBytes, [mineA, mineB, theirs]);
    expect(seeded).toMatchObject({ replaced: 0, added: 3 });

    const again = injectBuildsIntoCache(seeded.bytes, [
      ourBuild(HERO_A, "Vibelock — Hero A (Eternus)"),
    ]);
    expect(again).toMatchObject({ replaced: 1, added: 0 });
    const blobs = blobsIn(again.bytes);
    expect(blobs).toContain(hex(theirs)); // the player's build survives
    expect(blobs).toContain(hex(mineB)); // so does ours for the other hero
    expect(blobs).not.toContain(hex(mineA)); // only the same-hero Vibelock entry went
  });

  it("leaves entries it cannot parse exactly where they are", () => {
    // testBlob is not a valid envelope; it must not be mistaken for a replaceable build.
    const seeded = injectBuildsIntoCache(cacheBytes, [testBlob]);
    const again = injectBuildsIntoCache(seeded.bytes, [
      ourBuild(HERO_A, "Vibelock — Hero A (Oracle+)"),
    ]);
    expect(again).toMatchObject({ replaced: 0, added: 1 });
    expect(blobsIn(again.bytes)).toContain(hex(testBlob));
  });
});

const HERO_A = 15;
const HERO_B = 27;

/** A minimal but genuinely well-formed envelope: what readHeroBuildInfo has to be able to read back
 * out of what encodeHeroBuild writes in. Built by the real encoder so the two stay in step. */
function ourBuild(heroId: number, name: string): Uint8Array {
  return encodeHeroBuild(
    {
      hero: { id: heroId, name: `Hero ${heroId}` },
      rankLabel: "Oracle+",
      phases: [],
      overtimeBuys: [],
      overtimeSell: [],
      population: { matches: 1000, baselineWinRate: 0.5 },
    } as unknown as Parameters<typeof encodeHeroBuild>[0],
    { name, timestamp: 1_750_000_000 },
  );
}

const hex = (b: Uint8Array) =>
  [...b].map((x) => x.toString(16).padStart(2, "0")).join("");

/** Every binary blob in an emitted text-KV3 file, as its hex payload — enough to check what an
 * injection added and what it left alone, without re-implementing the reader. */
function blobsIn(textBytes: Uint8Array): string[] {
  const text = new TextDecoder().decode(textBytes);
  return [...text.matchAll(/#\[([0-9a-f\s]*)\]/g)].map((m) =>
    m[1].replace(/\s+/g, ""),
  );
}

describe("parseTextKv3", () => {
  // The reader exists because our own output comes back at us: export twice without launching the
  // game in between and the second read is of a text file we wrote. Round-tripping the REAL cache
  // file is the strongest available statement that the two halves agree.
  it("round-trips the real cache file through the text writer", () => {
    const tree = parseBinaryKv3(cacheBytes);
    const text = encodeTextKv3(tree);
    expect(jsonable(parseTextKv3(text))).toEqual(jsonable(tree));
  });

  it("round-trips the shapes the writer can emit", () => {
    const tree = new Map<string, Kv3Value>([
      ["ints", [1, 2, 3]], // inline scalar array
      ["longer", [1, 2, 3, 4, 5, 6, 7]], // one-per-line array
      ["dbl", new Kv3Double(1)], // integral double keeps its .0
      ["rounded", new Kv3Double(0.123457)],
      ["neg", -42],
      ["big", 9007199254740993n], // past 2^53 — must come back as bigint, not a lossy number
      ["0weird key", true],
      ["nul", null],
      ["no", false],
      ["str", "a string with = and { and , in it"],
      ["blob", Uint8Array.from([0, 255, 16])],
      ["empty blob", new Uint8Array(0)],
      ["empty map", new Map()],
      ["empty list", []],
      ["nested", new Map<string, Kv3Value>([["inner", [new Map()]]])],
      ["flagged", new Kv3Flagged("resource", "x.vmdl")],
    ]);
    expect(jsonable(parseTextKv3(encodeTextKv3(tree)))).toEqual(jsonable(tree));
    // bigint must not have silently become a float on the way back.
    const back = parseTextKv3(encodeTextKv3(tree)) as Map<string, Kv3Value>;
    expect(typeof back.get("big")).toBe("bigint");
    expect(back.get("dbl")).toBeInstanceOf(Kv3Double);
  });

  it("routes each format to the right reader", () => {
    expect(isTextKv3(cacheBytes)).toBe(false);
    const text = new TextEncoder().encode(
      encodeTextKv3(parseBinaryKv3(cacheBytes)),
    );
    expect(isTextKv3(text)).toBe(true);
    expect(jsonable(parseKv3(text))).toEqual(jsonable(parseKv3(cacheBytes)));
  });
});

describe("encodeTextKv3", () => {
  it("mirrors the Python writer's formatting quirks", () => {
    const tree = new Map<string, Kv3Value>([
      ["ints", [1, 2, 3]], // ≤6 scalars → same line
      ["longer", [1, 2, 3, 4, 5, 6, 7]], // >6 → one per line
      ["dbl", new Kv3Double(1)], // doubles keep .0
      ["rounded", new Kv3Double(0.12345678)], // …and round to 6 places
      ["0weird key", true], // non-identifier keys get quoted
      ["blob", Uint8Array.from([0, 255])],
      ["empty", new Map()],
    ]);
    expect(encodeTextKv3(tree)).toBe(
      `<!-- kv3 encoding:text:version{e21c7f3c-8a33-41c5-9977-a76d3a32aa0d} format:generic:version{7412167c-06e9-4698-aff2-e63eb59037e7} -->
{
\tints = [1, 2, 3]
\tlonger = 
\t[
\t\t1,
\t\t2,
\t\t3,
\t\t4,
\t\t5,
\t\t6,
\t\t7,
\t]
\tdbl = 1.0
\trounded = 0.123457
\t"0weird key" = true
\tblob = #[00 ff]
\tempty = 
\t{
\t}
}
`,
    );
  });
});
