/// <reference types="node" />
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
  Kv3Double,
  encodeTextKv3,
  parseBinaryKv3,
  type Kv3Value,
} from "./kv3";
import { injectBuildIntoCache } from "./heroBuildCache";

// A real (binary v5, LZ4) cache file, with reference outputs generated by the Python `keyvalues3`
// library the Pyodide-based reader used — the parse tree as JSON, and the text-KV3 result of the
// exact injection the shipped Python glue performed. Regenerate with scripts/gen-kv3-fixtures.py.
const FIXTURES = new URL("../test/fixtures/", import.meta.url);
const cacheBytes = new Uint8Array(
  readFileSync(new URL("cached_hero_builds.kv3", FIXTURES)),
);
const expectedTree = JSON.parse(
  readFileSync(new URL("kv3-tree.json", FIXTURES), "utf8"),
);
const expectedInjected = readFileSync(new URL("kv3-injected.kv3", FIXTURES));

// The same deterministic stand-in blob the fixture generator appended.
const testBlob = Uint8Array.from({ length: 64 }, (_, i) => (i * 37 + 11) & 0xff);

/** The Python fixture's JSON encoding: Maps → objects, blobs → {$bytes: hex}, doubles unwrapped. */
function jsonable(v: Kv3Value): unknown {
  if (v instanceof Uint8Array)
    return {
      $bytes: [...v].map((b) => b.toString(16).padStart(2, "0")).join(""),
    };
  if (v instanceof Map)
    return Object.fromEntries([...v].map(([k, x]) => [k, jsonable(x)]));
  if (Array.isArray(v)) return v.map(jsonable);
  if (v instanceof Kv3Double) return v.value;
  return v;
}

describe("parseBinaryKv3", () => {
  it("parses a real cache file identically to Python keyvalues3", () => {
    expect(jsonable(parseBinaryKv3(cacheBytes))).toEqual(expectedTree);
  });

  it("rejects non-KV3 bytes with a useful message", () => {
    expect(() => parseBinaryKv3(new Uint8Array(64))).toThrow(/not a binary kv3/i);
  });

  it("names older KV3 versions instead of failing cryptically", () => {
    const v4 = new Uint8Array(cacheBytes);
    v4[0] = 0x04;
    expect(() => parseBinaryKv3(v4)).toThrow(/version 4/);
  });
});

describe("injectBuildIntoCache", () => {
  it("matches the Python pipeline byte-for-byte", () => {
    const out = injectBuildIntoCache(cacheBytes, testBlob);
    expect(Buffer.from(out).equals(expectedInjected)).toBe(true);
  });

  it("rejects a KV3 file without a Favorites list", () => {
    // Text KV3 isn't binary KV3 — but any parseable file lacking Favorites hits the same guard.
    expect(() => injectBuildIntoCache(new Uint8Array(64), testBlob)).toThrow();
  });
});

describe("encodeTextKv3", () => {
  it("mirrors the Python writer's formatting quirks", () => {
    const tree = new Map<string, Kv3Value>([
      ["ints", [1, 2, 3]], // ≤6 scalars → same line
      ["longer", [1, 2, 3, 4, 5, 6, 7]], // >6 → one per line
      ["dbl", new Kv3Double(1)], // doubles keep .0
      ["rounded", new Kv3Double(0.12345678)], // …and round to 6 places
      ["0weird key", true], // non-identifier keys get quoted
      ["blob", Uint8Array.from([0, 255])],
      ["empty", new Map()],
    ]);
    expect(encodeTextKv3(tree)).toBe(
      `<!-- kv3 encoding:text:version{e21c7f3c-8a33-41c5-9977-a76d3a32aa0d} format:generic:version{7412167c-06e9-4698-aff2-e63eb59037e7} -->
{
\tints = [1, 2, 3]
\tlonger = 
\t[
\t\t1,
\t\t2,
\t\t3,
\t\t4,
\t\t5,
\t\t6,
\t\t7,
\t]
\tdbl = 1.0
\trounded = 0.123457
\t"0weird key" = true
\tblob = #[00 ff]
\tempty = 
\t{
\t}
}
`,
    );
  });
});
